name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and tag image
        run: docker build -t ttl.sh/smps-backend-docker:5m .
        
      - name: Push To ttl.sh
        run: docker push ttl.sh/smps-backend-docker:5m
